name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2      
    - name: Define runtime for build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101    
    - name: Build with dotnet
      run: dotnet build --configuration Release    
    - name: Generate NuGet package
      run: |  
        cd LessPaper.Shared.Queueing
        dotnet pack -c Release 
  
  unit_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout
      uses: actions/checkout@v2      
    - name: Define runtime for unit_test   
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101      
    - name: Run tests
      run: |
        cd ./LessPaper.Shared.Queueing.UnitTest
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./LessPaper.Shared.Queueing.UnitTest/TestResults/coverage.info 

  integration_test:
    runs-on: ubuntu-latest
    needs: [build, unit_test]
    steps:
    - name: checkout
      uses: actions/checkout@v2      
    - name: Define runtime for test   
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101      
    - uses: getong/rabbitmq-action@v1.2
      with:
        rabbitmq version: '3.8.2-management-alpine'
        host port: 5672
        rabbitmq user: 'guest'
        rabbitmq password: 'guest'
    - name: Run tests
      run: |  
        cd LessPaper.Shared.Queueing.IntegrationTest
        dotnet test

  publish:
    runs-on: ubuntu-latest
    needs: [build, unit_test, integration_test]
    steps:
    - name: checkout
      uses: actions/checkout@v2      
    - name: Define runtime for publishing 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101        
    - name: Publish to NuGet
      uses: rohith/publish-nuget@v2.2.0
      with:
        PROJECT_FILE_PATH: LessPaper.Shared.Queueing/LessPaper.Shared.Queueing.csproj
        PACKAGE_NAME: LessPaper.Shared.Queueing
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}    